name: 'Execute Job'
description: 'Execute a job in Parasoft Continuous Testing Platform'
author: 'Parasoft'
branding:
  icon: 'aperture'
  color: 'blue'
inputs:
  ctpUrl:
    required: true
    description: 'CTP URL'
  ctpUsername:
    required: true
    description: 'CTP Username'
  ctpPassword:
    required: true
    description: 'CTP Password'
  ctpJob:
    required: true
    description: 'CTP Test Execution Job Name'
  abortOnTimeout:
    required: false
    description: 'Abort the job after timeout exceeded'
  timeoutInMinutes:
    required: false
    description: 'Timeout value in minutes'
  publishReport:
    required: false
    description: 'Publish test execution results to DTP'
  dtpUrl:
    required: false
    description: 'DTP URL'
  dtpUsername:
    required: false
    description: 'DTP Username'
  dtpPassword:
    required: false
    description: 'DTP Password'
  dtpProject:
    required: false
    description: 'DTP Project Name'
  buildId:
    required: false
    description: 'Build ID to send to DTP'
  sessionTag:
    required: false
    description: 'Session Tag to send to DTP'
  appendEnvironment:
    required: false
    description: 'Append the test variable set environment name to the session tag'
runs:
  using: 'node12'
  main: 'dist/index.js'
